version: '3'



services:

    mysql:

        image: hshar/mysql:5.5

        restart: always

        ports:

            - "3306:3306"

    webapp:

        depends_on:

            - mysql

        image: hshar/webapp

        restart: always

        ports:

            - "8001:80"
